[package]
name = "test_1"
version = "0.1.0"
authors = ["Ayush Singh <aks.haloboy777@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
